Just saw this on Python pypy-3.7 Tests :

{code}
py run-test: commands[0] | coverage run -pm unittest discover --buffer --failfast
F
======================================================================
FAIL: test_minimum_speed (avro.test.test_bench.TestBench)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/avro/avro/lang/py/avro/test/test_bench.py", line 57, in test_minimum_speed
    .format(MAX_WRITE_SECONDS, NUMBER_OF_TESTS))
AssertionError: 3.111036313999989 not less than 3 : Took longer than 3 second(s) to write the test file with 10000 values.
{code}

This might be a performance regression, but it might also just be a busy build system.