Example failure:
{code}
16:54:32 ======================================================================
16:54:32 FAIL: test_big_query_write_new_types (apache_beam.io.gcp.bigquery_write_it_test.BigQueryWriteIntegrationTests)
16:54:32 ----------------------------------------------------------------------
16:54:32 Traceback (most recent call last):
16:54:32   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python35_PR/src/sdks/python/apache_beam/io/gcp/bigquery_write_it_test.py", line 229, in test_big_query_write_new_types
16:54:32     write_disposition=beam.io.BigQueryDisposition.WRITE_EMPTY))
16:54:32   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python35_PR/src/sdks/python/apache_beam/pipeline.py", line 426, in __exit__
16:54:32     self.run().wait_until_finish()
16:54:32   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python35_PR/src/sdks/python/apache_beam/pipeline.py", line 406, in run
16:54:32     self._options).run(False)
16:54:32   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python35_PR/src/sdks/python/apache_beam/pipeline.py", line 419, in run
16:54:32     return self.runner.run_pipeline(self, self._options)
16:54:32   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python35_PR/src/sdks/python/apache_beam/runners/direct/test_direct_runner.py", line 51, in run_pipeline
16:54:32     hc_assert_that(self.result, pickler.loads(on_success_matcher))
16:54:32 AssertionError: 
16:54:32 Expected: (Expected data is [(0.33, Decimal('10'), b'\xab\xac', datetime.date(3000, 12, 31), datetime.time(23, 59, 59), datetime.datetime(2018, 12, 31, 12, 44, 31), datetime.datetime(2018, 12, 31, 12, 44, 31, 744957, tzinfo=<UTC>), 'POINT(30 10)'), (0.33, None, None, None, None, None, None, None), (None, Decimal('10'), None, None, None, None, None, None), (None, None, b'\xab\xac', None, None, None, None, None), (None, None, None, datetime.date(3000, 12, 31), None, None, None, None), (None, None, None, None, datetime.time(23, 59, 59), None, None, None), (None, None, None, None, None, datetime.datetime(2018, 12, 31, 12, 44, 31), None, None), (None, None, None, None, None, None, datetime.datetime(2018, 12, 31, 12, 44, 31, 744957, tzinfo=<UTC>), None), (None, None, None, None, None, None, None, 'POINT(30 10)')])
16:54:32      but: 
16:54:32 
{code}

I've managed to recreated this locally on my workstation. The issue seems to be incorrect usage of the BigQuery client library. PR forthcoming.