Random tests fails on TC with the very same error (table name is varying though):
{code:java}
[14:04:04][executesColocatedWithMappedKey] java.util.concurrent.CompletionException
[14:04:04][executesColocatedWithMappedKey] java.util.concurrent.CompletionException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 13 to line 1, column 16: Object 'TEST' not found
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 13 to line 1, column 16: Object 'TEST' not found
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'TEST' not found
{code}
Â 

Looks like the root cause of this problem is race in between of completion of the future returned by {{TableManager#createTableAsync}} invocation and committing a temporal value of {{calciteSchemaVv}} (which was assigned by the event handling) by revision update callback.

Example: ItComputeTest.executesColocatedWithMappedKey is flaky with exception above.