Failed again with same error message.

One more

Failed again.

Did not monitor the build recently, but saw 2 more failures in the last 2 days... I assume it did fail regularly in the meantime, too.

Failed again.

Failed again.

And one more.

Failed again.

Failed again.

And one more (different stack trace)
{quote}[2021-12-01 02:54:02,641] ERROR Extensions provided in login context without a token (org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule:318) java.io.IOException: Extensions provided in login context without a token at org.apache.kafka.common.security.oauthbearer.internals.unsecured.OAuthBearerUnsecuredLoginCallbackHandler.handle(OAuthBearerUnsecuredLoginCallbackHandler.java:165) at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316) at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301){quote}

And one more.

Failed again.

One more.

And one more.

One more on 3.1 branch.

One more.

